### ISSUE TITLE
How to disable check

### ISSUE THREAD

**Issue by emilyanncr** [nikitastupin/param-miner-doc#1]
First off, thanks for your documentation. As you're aware this tool legit has little to none.  In your documentation, you break down the options by saying, for example: "if checked: Param Miner adds fcbz=1 URL parameter to every request in order to avoid cache hits".  Where do we have control over whether something is checked? Is there a menu of sorts I can not find? I'm using Burp Suite Pro version on windows machine.  Thanks!

**Comment by nikitastupin** [comment]
Hi @emilyanncr 

I'm glad that you've found this project helpful. Here are steps to open Param Miner settings:

<img width="1440" alt="Screen Shot 2021-07-01 at 12 46 52" src="https://user-images.githubusercontent.com/18281368/124104123-9ec48580-da6a-11eb-8817-d3e0947e2b9d.png">

<img width="1440" alt="Screen Shot 2021-07-01 at 12 49 11" src="https://user-images.githubusercontent.com/18281368/124104263-c0be0800-da6a-11eb-8e5f-3a37c0d2df25.png">

**Comment by emilyanncr** [comment]
yeah I felt really dumb after seeing that!  Thanks for getting back to me right away!!
